"""Weighted player model with backtest correlation (R^2).

Public behavior being mirrored (NOT their code):

  * "Player ratings are generated by your personal weighting of a variety of
    factors" [S17]
  * Factors named publicly include Vegas Score, Lineup Order Percentile, Park
    Factor "and much more" [S17]; optimizer article also lists median
    projection, ceiling/floor, ownership, Pro Trends, consistency, upside,
    projected +/-, points-per-dollar [S16].
  * "The 'R2' number ... measures the correlation between the model's player
    ratings and historical Plus/Minus. For reference, 0 means no correlation,
    while 1 means perfect correlation." [S17]

The actual FantasyLabs factor library and weights are proprietary (I15).
Here the user supplies their own factor columns; we z-score them, dot with
user weights, and report Pearson r / r^2 against historical Plus/Minus —
matching the documented meaning of the R2 tile.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Mapping, Optional, Sequence

import numpy as np


@dataclass(frozen=True)
class ModelFactor:
    """One weighted input to a player model."""

    name: str
    weight: float
    higher_is_better: bool = True


@dataclass
class WeightedPlayerModel:
    factors: List[ModelFactor]
    min_history: int = 5

    _means: Dict[str, float] = field(default_factory=dict, repr=False)
    _stds: Dict[str, float] = field(default_factory=dict, repr=False)
    _fitted: bool = field(default=False, repr=False)

    def fit(self, factor_matrix: Mapping[str, np.ndarray]) -> "WeightedPlayerModel":
        """Learn z-score params per factor column (unweighted params)."""
        for f in self.factors:
            if f.name not in factor_matrix:
                raise KeyError(f"missing factor column: {f.name}")
            col = np.asarray(factor_matrix[f.name], dtype=float)
            if col.size == 0:
                raise ValueError(f"empty column for {f.name}")
            mu = float(np.mean(col))
            sd = float(np.std(col, ddof=1)) if col.size > 1 else 0.0
            self._means[f.name] = mu
            self._stds[f.name] = sd if sd > 0 else 1.0
        self._fitted = True
        return self

    def ratings(self, factor_matrix: Mapping[str, np.ndarray]) -> np.ndarray:
        """Weighted sum of z-scored factors -> player ratings (any scale)."""
        if not self._fitted:
            raise RuntimeError("call fit() first")
        lengths = {len(np.asarray(factor_matrix[f.name])) for f in self.factors}
        if len(lengths) != 1:
            raise ValueError("factor columns must share one length")
        n = lengths.pop()
        out = np.zeros(n, dtype=float)
        for f in self.factors:
            col = np.asarray(factor_matrix[f.name], dtype=float)
            z = (col - self._means[f.name]) / self._stds[f.name]
            if not f.higher_is_better:
                z = -z
            out += f.weight * z
        return out

    def backtest(self,
                 factor_matrix: Mapping[str, np.ndarray],
                 historical_plus_minus: Sequence[float]) -> Dict[str, float]:
        """Return {'r': pearson_r, 'r2': pearson_r^2, 'n': n} — the meaning of
        the models-page R2 tile [S17]."""
        if not self._fitted:
            raise RuntimeError("call fit() first")
        ratings = self.ratings(factor_matrix)
        hist = np.asarray(historical_plus_minus, dtype=float)
        if ratings.shape != hist.shape:
            raise ValueError("rating/historical length mismatch")
        n = hist.size
        if n < self.min_history:
            return {"r": float("nan"), "r2": float("nan"), "n": float(n)}
        if np.std(ratings) == 0 or np.std(hist) == 0:
            return {"r": 0.0, "r2": 0.0, "n": float(n)}
        r = float(np.corrcoef(ratings, hist)[0, 1])
        if np.isnan(r):
            return {"r": float("nan"), "r2": float("nan"), "n": float(n)}
        return {"r": r, "r2": r * r, "n": float(n)}


def vegas_score_percentile(implied_team_points: float,
                           historical_implied_distribution: Sequence[float],
                           opponent: bool = True) -> float:
    """Vegas Score demo helper.

    Tutorial example: "93 Vegas Score ... ranks in the bottom 7 percent
    historically" for the *opposing* team's implied run projection [S17] —
    i.e., low opponent implied output => high (good) Vegas Score for our
    hitters. We return 0..100 where 100 = most favorable.
    """
    ref = np.asarray(historical_implied_distribution, dtype=float)
    if ref.size == 0:
        raise ValueError("empty reference distribution")
    if opponent:
        # lower implied for opponent => better for us => higher percentile
        below = np.sum(ref < implied_team_points)
        return float(100.0 * below / ref.size)
    below = np.sum(ref < implied_team_points)
    return float(100.0 * below / ref.size)
